spring:

  application:
    name: uudomi

  # DB 설정
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

 #JPA 설정
 #Dialect 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력
        format_sql: true #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현
        use_sql_comments: true #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력
        hbm2ddl:
          auto: none # entity 패키지를 기준으로 테이블 생성(DB초기화 전략) ->update , none 등 있음

server:
  servlet:
    encoding:
      force-response: true
  port: 8080